server:
  port: 8888
spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: r1
              uri: lb://DEPARTMENT-MICROSERVICE
              predicates:
                - Path= /api/departments/**
            - id: r2
              uri: lb://TEACHER-MICROSERVICE
              predicates:
                - Path= /api/teachers/**
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
      instance:
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
