server:
  port: 8888
spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: r1
              uri: lb://DEPARTMENT-MICROSERVICE
              predicates:
                - Path= /api/departments/**
            - id: r2
              uri: lb://TEACHER-MICROSERVICE
              predicates:
                - Path= /api/teachers/**
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
