spring:
  application:
    name: "configuration-server"
  profiles:
#    active: native
    active: git

  cloud:
    config:
      server:
          git:
            uri: https://github.com/CanseFr/config-repo.git
            default-label: main
            clone-on-start: true
        #        native:
#          search-locations: "classpath:/config"
#          search-locations: file:/Users/canse/Documents/java/disco-springcloud/config-repo

server:
  port: 9999