spring:
  application:
    name: "configuration-server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config"
          search-locations: file:/Users/canse/Documents/java/disco-springcloud/config-repo

server:
  port: 9999