server:
  port: 8080

spring:
  config:
#    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
    import: optional:configserver:http://localhost:9999
  application:
    name: department-microservice
  profiles:
    active: prod

  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

  # --- Pas de Config Server : tout est en dur ici
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

  datasource:
    url: jdbc:h2:mem:depdb
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# --- Eureka: attention aux clés (serviceUrl.defaultZone)
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka
#      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

build:
  version: "1.1"

author:
  name: "Canse Dep"
  email: "ouaisouais@gmail.com"


#spring:
#  profiles:
#    active: "prod"
#  config:
#    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
##    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
#  application:
#    name: department-microservice
#
#  datasource:
#    url: 'jdbc:h2:mem:depdb'
#  h2:
#    console:
#      enabled: true
#
#  #    url: jdbc:mysql://mysqldb:3306/test?useSSL=false&serverTimezone=UTC
#  #    username: root
#  #    password: Rootoorn
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  #    properties:
#  #      hibernate:
#  #        dialect: org.hibernate.dialect.MySQLDialect
#  cloud:
#    config:
#      enabled: true
#    discovery:
#      enabled: true
#  eureka:
#    client:
#      service-url:
#        defaultZone: http://eureka-server:8761/eureka
##        defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#eureka:
#  instance:
#    prefer-ip-address: true
#build:
#  version: 1.1
#author:
#  name: "Canse Dep"
#  email: "ouaisouais@gmail.com"
#
#server:
#  port: 8080
