spring:
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:9999"
  application:
    name: department-microservice

  datasource:
    url: 'jdbc:h2:mem:depdb'
  h2:
    console:
      enabled: true

#    url: jdbc:mysql://mysqldb:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: Rootoorn

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    prefer-ip-address: true

build:
  version: 1.1
author:
  name: "Canse Dep"
  email: "ouaisouais@gmail.com"