server:
  port: 8081

spring:
  config:
#    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
    import: optional:configserver:http://localhost:9999
  application:
    name: teacher-microservice
  profiles:
    active: prod

  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

  datasource:
    url: 'jdbc:h2:mem:teacherdb'
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka
  #      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
