server:
  port: 8081
spring:
  application:
    name: teacher-microservice

  datasource:
    url: 'jdbc:h2:mem:teacherdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
