server:
  port: 8081

spring:
  application:
    name: teacher-microservice
  profiles:
    active: prod

  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

  datasource:
    url: 'jdbc:h2:mem:teacherdb'
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
